// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'prototype/**',
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.next-dev/**',
      '**/next-env.d.ts',
      'tests/fixtures/site/**',
      // Generated by `npx unframer` (see apps/web/framer/README.md) — not hand-authored, don't lint.
      'apps/web/framer/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // Phase 1: keep defaults; revisit rule tuning once real application code lands.
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
);
