// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project bde45ab61ae59900 "Rejuvenated Takeaways", do not edit manually */
"use client";

// virtual:scroll
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/5La8aW1sIB6fvXaovdQB/IRLdDY3hrVdVme5VOSOy/il9OxxPTP.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/AoQAFDY644LDNQ7s3szT/3u60lLOoADWXFvcvY5Ek/StickyScrollStory_2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	useIsStaticRenderer,
} from "unframer";
import { useEffect, useRef, useState, startTransition } from "react";
import { motion, useScroll, useTransform } from "unframer";
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var DEFAULT_TEXTS = [
	"Struggling with poor conversion or high CAC? You're probably not feeding the algorithm enough quality statics.",
	"While video ads are great at bringing people into the funnel, statics are fundamental for bottom-of-funnel conversion.",
	"The data proves it. An analysis of 25 top D2C brands shows that 62% of their top-performing ads are statics.",
	"And with Meta's new persona-based targeting algorithm, the demand for varied statics is only going to become greater.",
	"AI can help with the production of statics, but the technology is not yet advanced enough to deliver the complete package.",
];
function getSafeTexts(texts) {
	if (!Array.isArray(texts) || texts.length === 0) return DEFAULT_TEXTS;
	return texts.slice(0, 5);
}
function clampIndex(index, total) {
	return Math.min(Math.max(Math.round(index || 0), 0), Math.max(total - 1, 0));
}
function AnimatedText({
	text,
	index,
	total,
	scrollYProgress,
	textColor,
	font,
	isMobile,
	mobileFontSize,
}) {
	const segment = 1 / total;
	const startProgress = index * segment;
	const midProgress = Math.min(startProgress + segment * 0.3, 1);
	const endProgress = Math.min(startProgress + segment * 0.7, 1);
	const opacity = useTransform(
		scrollYProgress,
		[startProgress, midProgress, endProgress],
		[0, 1, 0],
	);
	const y = useTransform(
		scrollYProgress,
		[startProgress, midProgress, endProgress],
		[30, 0, -30],
	);
	return (
		<motion.div
			suppressHydrationWarning={true}
			style={{
				position: "absolute",
				top: 0,
				left: 0,
				right: 0,
				color: textColor,
				textAlign: "center",
				...font,
				...(isMobile && {
					fontSize: mobileFontSize,
				}),
				opacity,
				y,
			}}
		>
			{text}
		</motion.div>
	);
}
function StaticStickyScrollStory(props) {
	const {
		activeIndex = 0,
		textColor = "#000000",
		backgroundColor = "#FFFFFF",
		activeDotColor = "#707070",
		inactiveDotColor = "#D9D9D9",
		font = {},
		style,
	} = props;
	const texts = getSafeTexts(props.texts);
	const previewIndex = clampIndex(activeIndex, texts.length);
	return (
		<div
			suppressHydrationWarning={true}
			style={{
				...style,
				width: "100%",
				height: "100%",
				minHeight: 400,
				position: "relative",
				overflow: "hidden",
				backgroundColor,
				display: "flex",
				alignItems: "center",
				justifyContent: "center",
			}}
		>
			<div
				suppressHydrationWarning={true}
				style={{
					position: "absolute",
					left: "clamp(24px, 5vw, 80px)",
					top: "50%",
					transform: "translateY(-50%)",
					display: "flex",
					flexDirection: "column",
					gap: 10,
					alignItems: "center",
				}}
			>
				{texts.map((_, index) => (
					<div
						suppressHydrationWarning={true}
						style={{
							width: 13,
							height: 13,
							borderRadius: 999,
							backgroundColor:
								index === previewIndex ? activeDotColor : inactiveDotColor,
						}}
					/>
				))}
			</div>
			<div
				suppressHydrationWarning={true}
				style={{
					width: "calc(100% - 200px)",
					maxWidth: 760,
					padding: "0 24px",
					boxSizing: "border-box",
					color: textColor,
					textAlign: "center",
					...font,
				}}
			>
				{texts[previewIndex]}
			</div>
		</div>
	);
}
function InteractiveStickyScrollStory(props) {
	const {
		textColor = "#000000",
		backgroundColor = "#FFFFFF",
		activeDotColor = "#707070",
		inactiveDotColor = "#D9D9D9",
		font = {},
		mobileFontSize = "24px",
		style,
	} = props;
	const texts = getSafeTexts(props.texts);
	const sectionRef = useRef(null);
	const [currentActiveIndex, setCurrentActiveIndex] = useState(0);
	const [isMobile, setIsMobile] = useState(false);
	useEffect(() => {
		if (typeof __unframerWindow === "undefined") return;
		const checkMobile = () => {
			startTransition(() => {
				setIsMobile(__unframerWindow.innerWidth < 1024);
			});
		};
		checkMobile();
		__unframerWindow.addEventListener("resize", checkMobile);
		return () => {
			__unframerWindow.removeEventListener("resize", checkMobile);
		};
	}, []);
	const { scrollYProgress } = useScroll({
		target: sectionRef,
		offset: ["start start", "end end"],
	});
	useEffect(() => {
		return scrollYProgress.on("change", (latest) => {
			const newIndex = Math.min(
				Math.floor(latest * texts.length),
				texts.length - 1,
			);
			startTransition(() => {
				setCurrentActiveIndex(Math.max(newIndex, 0));
			});
		});
	}, [scrollYProgress, texts.length]);
	const dotsOpacity = useTransform(
		scrollYProgress,
		[0, 0.1, 0.9, 1],
		[0, 1, 1, 0],
	);
	return (
		<div
			suppressHydrationWarning={true}
			ref={sectionRef}
			style={{
				...style,
				height: "800vh",
				backgroundColor,
				position: "relative",
				overflow: "clip",
			}}
		>
			<div
				suppressHydrationWarning={true}
				style={{
					position: "sticky",
					top: 0,
					width: "100%",
					height: "100vh",
					backgroundColor,
					display: "flex",
					flexDirection: "column",
					alignItems: "center",
					justifyContent: isMobile ? "flex-start" : "center",
					zIndex: 1,
					overflow: "clip",
					paddingTop: isMobile ? "38vh" : 0,
					boxSizing: "border-box",
				}}
			>
				{!isMobile && (
					<motion.div
						suppressHydrationWarning={true}
						style={{
							position: "absolute",
							left: 80,
							top: "50%",
							transform: "translateY(calc(-50% - 27px))",
							display: "flex",
							flexDirection: "column",
							gap: 10,
							alignItems: "center",
							opacity: dotsOpacity,
						}}
					>
						{texts.map((_, index) => (
							<div
								suppressHydrationWarning={true}
								style={{
									width: 13,
									height: 13,
									borderRadius: 999,
									backgroundColor:
										index === currentActiveIndex
											? activeDotColor
											: inactiveDotColor,
									transition: "background-color 0.3s ease",
								}}
							/>
						))}
					</motion.div>
				)}
				<div
					suppressHydrationWarning={true}
					style={{
						maxWidth: isMobile ? "100%" : 760,
						width: isMobile ? "100%" : 760,
						display: "flex",
						flexDirection: "column",
						alignItems: "center",
						...(isMobile && {
							padding: "0 24px",
							boxSizing: "border-box",
						}),
					}}
				>
					<div
						suppressHydrationWarning={true}
						style={{
							color: textColor,
							textAlign: "center",
							...font,
							...(isMobile && {
								fontSize: mobileFontSize,
							}),
							position: "relative",
							width: "100%",
							minHeight: 200,
						}}
					>
						{texts.map((text, index) => (
							<AnimatedText
								suppressHydrationWarning={true}
								text={text}
								index={index}
								total={texts.length}
								scrollYProgress={scrollYProgress}
								textColor={textColor}
								font={font}
								isMobile={isMobile}
								mobileFontSize={mobileFontSize}
							/>
						))}
					</div>
				</div>
				{isMobile && (
					<motion.div
						suppressHydrationWarning={true}
						style={{
							position: "absolute",
							bottom: 60,
							left: 0,
							right: 0,
							margin: "auto",
							display: "flex",
							flexDirection: "column",
							gap: 5,
							alignItems: "center",
							opacity: dotsOpacity,
						}}
					>
						{texts.map((_, index) => (
							<div
								suppressHydrationWarning={true}
								style={{
									width: 18,
									height: index === currentActiveIndex ? 2 : 1.5,
									borderRadius: 1,
									backgroundColor:
										index === currentActiveIndex
											? activeDotColor
											: inactiveDotColor,
									transition: "background-color 0.3s ease, height 0.3s ease",
								}}
							/>
						))}
					</motion.div>
				)}
			</div>
		</div>
	);
}
function StickyScrollStory(props) {
	const isStaticRenderer = useIsStaticRenderer();
	if (isStaticRenderer) {
		return (
			<StaticStickyScrollStory suppressHydrationWarning={true} {...props} />
		);
	}
	return (
		<InteractiveStickyScrollStory suppressHydrationWarning={true} {...props} />
	);
}
addPropertyControls(StickyScrollStory, {
	texts: {
		type: ControlType.Array,
		title: "Texts",
		control: {
			type: ControlType.String,
			displayTextArea: true,
		},
		defaultValue: DEFAULT_TEXTS,
		maxCount: 5,
	},
	activeIndex: {
		type: ControlType.Number,
		title: "Canvas Preview",
		defaultValue: 0,
		min: 0,
		max: 4,
		step: 1,
		displayStepper: true,
	},
	font: {
		type: ControlType.Font,
		title: "Font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: "38px",
			variant: "Regular",
			letterSpacing: "-0.04em",
			lineHeight: "1.2em",
		},
	},
	textColor: {
		type: ControlType.Color,
		title: "Text Color",
		defaultValue: "#000000",
	},
	backgroundColor: {
		type: ControlType.Color,
		title: "Background",
		defaultValue: "#FFFFFF",
	},
	activeDotColor: {
		type: ControlType.Color,
		title: "Active Dot",
		defaultValue: "#707070",
	},
	inactiveDotColor: {
		type: ControlType.Color,
		title: "Inactive Dots",
		defaultValue: "#D9D9D9",
	},
	mobileFontSize: {
		type: ControlType.String,
		title: "Mobile Font Size",
		defaultValue: "24px",
	},
});

// /:https://framerusercontent.com/modules/5La8aW1sIB6fvXaovdQB/IRLdDY3hrVdVme5VOSOy/il9OxxPTP.js
var StickyScrollStoryFonts = getFonts(StickyScrollStory);
var serializationHash = "framer-luEjK";
var variantClassNames = {
	usSVpOkuM: "framer-v-xt6gcs",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "usSVpOkuM",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion2.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-xt6gcs",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"usSVpOkuM"}
						ref={refBinding}
						style={{
							backgroundColor: "rgb(255, 255, 255)",
							...style,
						}}
					>
						<ComponentViewportProvider suppressHydrationWarning={true}>
							<SmartComponentScopedContainer
								suppressHydrationWarning={true}
								className={"framer-x5zy8p-container"}
								data-code-component-plugin-id={"84d4c1"}
								isAuthoredByUser={true}
								isModuleExternal={true}
								layoutDependency={layoutDependency}
								layoutId={"SxN0cJycZ-container"}
								nodeId={"SxN0cJycZ"}
								rendersWithMotion={true}
								scopeId={"il9OxxPTP"}
							>
								<StickyScrollStory
									suppressHydrationWarning={true}
									activeDotColor={"rgb(112, 112, 112)"}
									activeIndex={0}
									backgroundColor={"rgb(255, 255, 255)"}
									font={{
										fontFamily: '"Inter", "Inter Placeholder", sans-serif',
										fontSize: "38px",
										fontStyle: "normal",
										fontWeight: 400,
										letterSpacing: "-0.04em",
										lineHeight: "1.2em",
									}}
									height={"100%"}
									id={"SxN0cJycZ"}
									inactiveDotColor={"rgb(217, 217, 217)"}
									layoutId={"SxN0cJycZ"}
									mobileFontSize={"24px"}
									style={{
										height: "100%",
										width: "100%",
									}}
									textColor={"rgb(0, 0, 0)"}
									texts={[
										"Struggling with poor conversion or high CAC? You're probably not feeding the algorithm enough quality statics.",
										"While video ads are great at bringing people into the funnel, statics are fundamental for bottom-of-funnel conversion.",
										"The data proves it. An analysis of 25 top D2C brands shows that 62% of their top-performing ads are statics.",
										"And with Meta's new persona-based targeting algorithm, the demand for varied statics is only going to become greater.",
										"AI can help with the production of statics, but the technology is not yet advanced enough to deliver the complete package.",
									]}
									width={"100%"}
								/>
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	".framer-luEjK.framer-vghsmg, .framer-luEjK .framer-vghsmg { display: block; }",
	".framer-luEjK.framer-xt6gcs { height: 200px; position: relative; width: 200px; }",
	".framer-luEjK .framer-x5zy8p-container { bottom: -275px; flex: none; left: 0px; position: absolute; right: -513px; top: 0px; }",
];
var Frameril9OxxPTP = withCSS(Component, css, "framer-luEjK");
var stdin_default = Frameril9OxxPTP;
Frameril9OxxPTP.displayName = "scroll";
Frameril9OxxPTP.defaultProps = {
	height: 200,
	width: 200,
};
addFonts(
	Frameril9OxxPTP,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...StickyScrollStoryFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:scroll
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	augiA20Il: {
		path: "/",
	},
};

// virtual:scroll
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"bde45ab61ae5990038f3998eba5b2ce60f65b74f55a6143df33126e84347fc6b"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ScrollFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"bde45ab61ae5990038f3998eba5b2ce60f65b74f55a6143df33126e84347fc6b"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var scroll_default = ComponentWithRoot;
export { scroll_default as default };
